import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import { Inter } from "next/font/google";
import BootstrapClient from "../components/BootstrapClient.js";
import AppNavbar from "@/components/Navbar";
import { GearProvider } from "@/context/GearContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <GearProvider>
                    <AppNavbar />
                    <main>{children}</main>
                    <BootstrapClient />
                </GearProvider>
            </body>
        </html>
    );
}
